// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ex03_ef_postgresql.Data;

#nullable disable

namespace ex03_ef_postgresql.Migrations
{
    [DbContext(typeof(TravelDbContext))]
    [Migration("20260329140432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DestinationTraveler", b =>
                {
                    b.Property<int>("DestinationsId")
                        .HasColumnType("integer");

                    b.Property<int>("TravelersId")
                        .HasColumnType("integer");

                    b.HasKey("DestinationsId", "TravelersId");

                    b.HasIndex("TravelersId");

                    b.ToTable("TravelerDestinations", (string)null);
                });

            modelBuilder.Entity("ex03_ef_postgresql.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "New York City, New York"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Paris, France"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tokyo, Japan"
                        });
                });

            modelBuilder.Entity("ex03_ef_postgresql.Models.Guide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Guides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Robby Rix"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sally Guide"
                        });
                });

            modelBuilder.Entity("ex03_ef_postgresql.Models.Passport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("TravelerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TravelerId")
                        .IsUnique();

                    b.ToTable("Passports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PassportNumber = "123456",
                            TravelerId = 1
                        });
                });

            modelBuilder.Entity("ex03_ef_postgresql.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuideId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GuideId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GuideId = 1,
                            Title = "City Walk"
                        },
                        new
                        {
                            Id = 2,
                            GuideId = 1,
                            Title = "Museum Tour"
                        },
                        new
                        {
                            Id = 3,
                            GuideId = 2,
                            Title = "Eiffel Tower"
                        },
                        new
                        {
                            Id = 4,
                            GuideId = 1,
                            Title = "Tour 4"
                        });
                });

            modelBuilder.Entity("ex03_ef_postgresql.Models.Traveler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Travelers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "John Doe"
                        });
                });

            modelBuilder.Entity("DestinationTraveler", b =>
                {
                    b.HasOne("ex03_ef_postgresql.Models.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ex03_ef_postgresql.Models.Traveler", null)
                        .WithMany()
                        .HasForeignKey("TravelersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ex03_ef_postgresql.Models.Passport", b =>
                {
                    b.HasOne("ex03_ef_postgresql.Models.Traveler", "Traveler")
                        .WithOne("Passport")
                        .HasForeignKey("ex03_ef_postgresql.Models.Passport", "TravelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Traveler");
                });

            modelBuilder.Entity("ex03_ef_postgresql.Models.Tour", b =>
                {
                    b.HasOne("ex03_ef_postgresql.Models.Guide", "Guide")
                        .WithMany("Tours")
                        .HasForeignKey("GuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guide");
                });

            modelBuilder.Entity("ex03_ef_postgresql.Models.Guide", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("ex03_ef_postgresql.Models.Traveler", b =>
                {
                    b.Navigation("Passport");
                });
#pragma warning restore 612, 618
        }
    }
}
