// <auto-generated />
using System;
using Howest.ex05.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace ex05_steam.Migrations
{
    [DbContext(typeof(SteamContext))]
    [Migration("20260329140650_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Howest.ex05.Models.Game", b =>
                {
                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<string>("AboutTheGame")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Achievements")
                        .HasColumnType("integer");

                    b.Property<int>("AveragePlaytime")
                        .HasColumnType("integer");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("English")
                        .HasColumnType("integer");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MedianPlaytime")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NegativeRatings")
                        .HasColumnType("integer");

                    b.Property<string>("Owners")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platforms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PositiveRatings")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequiredAge")
                        .HasColumnType("integer");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Name", "DetailedDescription", "AboutTheGame", "Developer", "Publisher" });

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SteamSpyTags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("AppId");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Howest.ex05.Models.Game", b =>
                {
                    b.OwnsOne("Howest.ex05.Models.SystemRequirements", "Requirements", b1 =>
                        {
                            b1.Property<int>("GameAppId");

                            b1.Property<string>("LinuxRequirements")
                                .IsRequired();

                            b1.Property<string>("MacRequirements")
                                .IsRequired();

                            b1.Property<string>("Minimum")
                                .IsRequired();

                            b1.Property<string>("PcRequirements")
                                .IsRequired();

                            b1.Property<string>("Recommended")
                                .IsRequired();

                            b1.HasKey("GameAppId");

                            b1.ToTable("Games");

                            b1
                                .ToJson("Requirements")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("GameAppId");
                        });

                    b.Navigation("Requirements")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
