// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RetailStoreAPI.Data;

#nullable disable

namespace RetailStoreAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RetailStoreAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gadgets and electronic devices",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apparel and accessories",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Groceries and consumables",
                            Name = "Food"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sports equipment and gear",
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("RetailStoreAPI.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SUMMER10",
                            ExpiresAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Percentage = 10.0
                        },
                        new
                        {
                            Id = 2,
                            Code = "SALE25",
                            ExpiresAt = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Percentage = 25.0
                        },
                        new
                        {
                            Id = 3,
                            Code = "FLASH50",
                            ExpiresAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Percentage = 50.0
                        });
                });

            modelBuilder.Entity("RetailStoreAPI.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Alice",
                            HiredAt = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Johnson",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Bob",
                            HiredAt = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Smith",
                            Role = "Cashier"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Carol",
                            HiredAt = new DateTime(2021, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Davis",
                            Role = "Stock"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "David",
                            HiredAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Wilson",
                            Role = "Cashier"
                        });
                });

            modelBuilder.Entity("RetailStoreAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DiscountId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DiscountId = 1,
                            Name = "Laptop Pro 15",
                            Price = 1299.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Wireless Earbuds",
                            Price = 89.99m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DiscountId = 2,
                            Name = "Smart Watch",
                            Price = 249.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            DiscountId = 3,
                            Name = "Running Jacket",
                            Price = 69.99m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Classic T-Shirt",
                            Price = 24.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Organic Coffee 1kg",
                            Price = 15.49m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            DiscountId = 1,
                            Name = "Protein Bars (12x)",
                            Price = 19.99m,
                            Stock = 180
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Name = "Tennis Racket",
                            Price = 119.99m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            DiscountId = 2,
                            Name = "Yoga Mat",
                            Price = 39.99m,
                            Stock = 90
                        });
                });

            modelBuilder.Entity("RetailStoreAPI.Models.Product", b =>
                {
                    b.HasOne("RetailStoreAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RetailStoreAPI.Models.Discount", "Discount")
                        .WithMany("Products")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("RetailStoreAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RetailStoreAPI.Models.Discount", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
