version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: steam-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: steamdb
    ports:
      - "5412:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: